default_job = "check"

[jobs.check]
command = ["cargo", "check", "--all-targets"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets"]
need_stdout = false

[jobs.test]
command = ["cargo", "nextest", "run"]
need_stdout = true

[keybindings]
t = "job:test"
c = "job:clippy"
